### ISSUE TITLE
Error Loading Java 45 Server/jvm.dll

### ISSUE THREAD

**Issue by NameLord** [ThisTestUser/FlashSuite#5]
![image](https://user-images.githubusercontent.com/27507408/118066975-5234c600-b3a8-11eb-9245-0c19cc0e101d.png)
Title and here.

Edit 1: Ok i found a fix for that.
If you have older versions of Java Please Uninstall them it won't work.
And install latest version of java right now i have Java 8 Update 281

**Comment by ThisTestUser** [comment]
That error is not related to this program, instead it has to do with your java installation.
